# Build file for artifact repos - exposes artifact content and metadata
ARTIFACT_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia - JLL artifact.\"\"\"

# Artifact content
filegroup(
    name = "files",
    srcs = glob(["**"], exclude = ["BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel", "_jll_artifact_meta.json"]),
    visibility = ["//visibility:public"],
)

# Metadata file for runtime artifact discovery
genrule(
    name = "metadata",
    outs = ["_jll_artifact_meta.json"],
    cmd = \"\"\"echo '{metadata_json}' > $@\"\"\",
)

# Combined artifact + metadata
filegroup(
    name = "artifact",
    srcs = [":files", ":metadata"],
    visibility = ["//visibility:public"],
)

# C++ integration: headers and shared libraries from the artifact
# This target can be used as a dep in cc_library/cc_binary rules
cc_library(
    name = "cc",
    hdrs = glob(["include/**/*.hpp", "include/**/*.h"], allow_empty = True),
    includes = ["include"],
    # srcs = glob(["lib/**/libcxxwrap_julia.so"], exclude = ["lib/*.so.*"], allow_empty = True),
    visibility = ["//visibility:public"],
)

# Make libcxxwrap_julia accessible for cc_import
exports_files(
    glob(["lib/*.so", "lib/*.so.*"], allow_empty = True),
    visibility = ["//visibility:public"],
)
"""
