load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files([
    "artifact.bzl",
    "hub.bzl",
    "jll.bzl",
    "pkg.bzl",
])

bzl_library(
    name = "bzl_lib",
    srcs = glob(["*.bzl"]),
    visibility = [
        "//extras/pkg:__pkg__",
        "//julia/pkg/private:__pkg__"
    ],
)
