HUB_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")

PACKAGES = {packages}

julia_library(
    name = "{name}",
    srcs = [],
    deps = [
        "@{name}__" + pkg
        for pkg in PACKAGES
    ],
    visibility = ["//visibility:public"],
)

[
    alias(
        name = pkg,
        actual = "@{name}__" + pkg,
        visibility = ["//visibility:public"],
    )
    for pkg in PACKAGES
]
"""
