# Build file for JLL packages - includes artifact dependencies via select()
JLL_PKG_BUILD_FILE_HEADER = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")

DEPENDENCIES = {dependencies}

"""

JLL_PKG_BUILD_FILE_CONFIG_SETTING = """\
config_setting(
    name = "{name}",
    constraint_values = {constraints},
)

"""

JLL_PKG_BUILD_FILE_ARTIFACT_SELECT = """\
# Platform-specific artifact selection for {artifact_name}
# Each artifact is downloaded to a separate repo and selected based on platform
filegroup(
    name = "artifact_{artifact_name}",
    srcs = select({{
{select_cases}
    }}),
)

"""

JLL_PKG_BUILD_FILE_FOOTER = """\
julia_library(
    name = "{name}",
    srcs = glob(
        include = [
            "src/**/*.jl",
            "ext/**/*.jl",
        ],
        allow_empty = True,
    ),
    data = glob(
        include = [
            "**",
        ],
        exclude = [
            "*.jl",
            "src/**/*.jl",
            "ext/**/*.jl",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
            "LICENSE",
            "**/docs/**",
            "**/contrib/**",
            "**/test/**",
            "**/.*",
        ],
        allow_empty = True,
    ){artifact_data},
    deps = [
        "@{hub_name}__" + dep
        for dep in DEPENDENCIES
    ],
    tags = [
        "julia_pkg_version={version}",
        "julia_pkg_uuid={uuid}",
    ],
    visibility = ["//visibility:public"],
)

alias(
    name = "{repo_name}",
    actual = "{name}",
    visibility = ["//visibility:public"],
)
"""
