PKG_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")

DEPENDENCIES = {dependencies}

julia_library(
    name = "{name}",
    srcs = glob(
        include = [
            "src/**/*.jl",
            "ext/**/*.jl",
        ],
        allow_empty = True,
    ),
    data = glob(
        include = [
            "**",
        ],
        exclude = [
            "*.jl",
            "src/**/*.jl",
            "ext/**/*.jl",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
            "LICENSE",
            "**/docs/**",
            "**/contrib/**",
            "**/test/**",
            "**/.*",
        ],
        allow_empty = True,
    ),
    deps = [
        "@{hub_name}__" + dep
        for dep in DEPENDENCIES
    ],
    tags = [
        "julia_pkg_version={version}",
        "julia_pkg_uuid={uuid}",
    ],
    visibility = ["//visibility:public"],
)

alias(
    name = "{repo_name}",
    actual = "{name}",
    visibility = ["//visibility:public"],
)
"""
