name: CI

on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

env:
  BAZEL_STARTUP_FLAGS: --bazelrc=${{ github.workspace }}/.github/github.bazelrc

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Setup Bazelrc
        run: |
          echo "common --keep_going" >> ./user.bazelrc

      # Build and Test the code
      - name: Test (Unix)
        run: bazel ${BAZEL_STARTUP_FLAGS[@]} test //...

  ci-format:
    runs-on: ubuntu-24.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Buildifier
        run: |
          wget "https://github.com/bazelbuild/buildtools/releases/download/v${BUILDIFIER_VERSION}/buildifier-linux-amd64" -O buildifier
          chmod +x ./buildifier
          ./buildifier -lint=warn -mode=check -warnings=all -r ${{ github.workspace }}
          rm ./buildifier
        env:
          BUILDIFIER_VERSION: 8.2.0
