"""Bazel tools for interfacing with Julia packages"""

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load(":pkg_utils.bzl",
    "add_annotation_args",
    "create_artifact_repos",
    "generate_jll_build_file",
)

_HUB_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")

PACKAGES = {packages}

julia_library(
    name = "{name}",
    srcs = [],
    deps = [
        "@{name}__" + pkg
        for pkg in PACKAGES
    ],
    visibility = ["//visibility:public"],
)

[
    alias(
        name = pkg,
        actual = "@{name}__" + pkg,
        visibility = ["//visibility:public"],
    )
    for pkg in PACKAGES
]
"""

_PKG_BUILD_FILE = """\
\"\"\"Autogenerated by rules_julia.\"\"\"

load("@rules_julia//julia:julia_library.bzl", "julia_library")

DEPENDENCIES = {dependencies}

julia_library(
    name = "{name}",
    srcs = glob(
        include = [
            "src/**/*.jl",
            "ext/**/*.jl",
        ],
        allow_empty = True,
    ),
    data = glob(
        include = [
            "**",
        ],
        exclude = [
            "*.jl",
            "src/**/*.jl",
            "ext/**/*.jl",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
            "LICENSE",
            "**/docs/**",
            "**/contrib/**",
            "**/test/**",
            "**/.*",
        ],
        allow_empty = True,
    ),
    deps = [
        "@{hub_name}__" + dep
        for dep in DEPENDENCIES
    ],
    tags = [
        "julia_pkg_version={version}",
        "julia_pkg_uuid={uuid}",
    ],
    visibility = ["//visibility:public"],
)

alias(
    name = "{repo_name}",
    actual = "{name}",
    visibility = ["//visibility:public"],
)
"""

def _pkg_hub_impl(repository_ctx):
    repository_ctx.file("WORKSPACE.bazel", """workspace(name = "{}")""".format(
        repository_ctx.name,
    ))

    repository_ctx.file("BUILD.bazel", _HUB_BUILD_FILE.format(
        name = repository_ctx.attr.hub_name,
        packages = json.encode_indent(repository_ctx.attr.packages, indent = " " * 4),
    ))

pkg_hub = repository_rule(
    implementation = _pkg_hub_impl,
    attrs = {
        "hub_name": attr.string(
            mandatory = True,
        ),
        "packages": attr.string_list(
            mandatory = True,
        ),
    },
)

def _read_lockfile_json(module_ctx, lockfile_path):
    """Read and parse the Manifest.bazel.json lockfile.

    Returns a dictionary mapping package names to package data including SHA256 hashes.
    """
    lockfile = module_ctx.path(lockfile_path)
    module_ctx.watch(lockfile)
    content = module_ctx.read(lockfile)

    # Parse JSON content
    packages = json.decode(content)

    return packages

def install(*, module_ctx, attrs, annotations = {}):
    """Instantiate the pkg module for the given `install` tag_class attributes.

    Args:
        module_ctx (module_ctx): The current module context.
        attrs (struct): The attributes from the `install` tag class.
        annotations (dict): Optional dictionary mapping package names to annotation data.

    Returns:
        str: The name of the hub repository for the current tag_class.
    """

    # Read the JSON lockfile
    packages = _read_lockfile_json(module_ctx, attrs.lockfile)

    # Get all package names for dependency filtering
    all_package_names = list(packages.keys())

    # Create repositories for all packages
    for package_name, package_data in packages.items():
        # Extract package information
        pkg_type = package_data.get("type", "http")  # default to http for backwards compatibility
        version = package_data.get("version", "")
        uuid = package_data.get("uuid", "")
        all_deps = package_data.get("deps", [])
        artifacts = package_data.get("artifacts", {})

        # Validate required fields
        if not uuid:
            fail("Package {} missing UUID in lockfile".format(package_name))

        # Filter dependencies to only include packages in this lockfile
        deps = [dep for dep in all_deps if dep in all_package_names]

        repo_name = "{}__{}".format(attrs.name, package_name)

        # Get annotations for this package if any
        package_annotations = annotations.get(package_name)

        # Check if this is a JLL package with artifacts
        is_jll_with_artifacts = artifacts and package_name.endswith("_jll")

        # Create artifact repos for JLL packages
        artifact_repos = {}
        if is_jll_with_artifacts:
            artifact_repos = create_artifact_repos(
                module_ctx,
                attrs.name,
                package_name,
                uuid,
                artifacts,
            )

        # Generate appropriate build file content
        if is_jll_with_artifacts and artifact_repos:
            build_file_content = generate_jll_build_file(
                package_name,
                deps,
                attrs.name,
                repo_name,
                version,
                uuid,
                artifact_repos,
            )
        else:
            # Standard package build file
            build_file_content = _PKG_BUILD_FILE.format(
                name = package_name,
                dependencies = deps,
                hub_name = attrs.name,
                repo_name = repo_name,
                version = version,
                uuid = uuid,
            )

        if pkg_type == "git":
            # Private package: use git_repository
            # This allows Bazel to use the host's git auth (SSH keys, credential helpers, etc.)
            remote = package_data.get("remote", "")
            tag = package_data.get("tag", "")

            if not remote:
                fail("Package {} has type 'git' but missing 'remote' field".format(package_name))
            if not tag:
                fail("Package {} has type 'git' but missing 'tag' field".format(package_name))

            git_repository_args = {
                "name": repo_name,
                "remote": remote,
                "tag": tag,
                "build_file_content": build_file_content,
            }

            # Apply patch-related attributes if annotations exist for this package
            if package_annotations:
                git_repository_args = add_annotation_args(
                    git_repository_args,
                    package_annotations
                )

            git_repository(**git_repository_args)

        elif pkg_type == "http":
            # Public package: use http_archive with integrity verification
            urls = package_data.get("urls", [])

            if not urls:
                fail("Package {} has type 'http' but missing 'urls' field".format(package_name))

            http_archive_args = {
                "name": repo_name,
                "urls": urls,
                "integrity": package_data.get("integrity", ""),
                "sha256": package_data.get("sha256", ""),
                "type": "tar.gz",
                "build_file_content": build_file_content,
            }

            # Apply patch-related attributes if annotations exist for this package
            if package_annotations:
                http_archive_args = add_annotation_args(
                    http_archive_args,
                    package_annotations
                )

            http_archive(**http_archive_args)

        else:
            fail("Package {} has unknown pkg_type: {}".format(package_name, pkg_type))

    # Create hub with all packages
    pkg_hub(
        name = attrs.name,
        hub_name = attrs.name,
        packages = list(packages.keys()),
    )

    return attrs.name
